### ISSUE TITLE
Cant access the second opened device registers

### ISSUE THREAD

**Issue by cagil-gumus** [ChimeraTK/DeviceAccess-PythonBindings#12]
Let's imagine 1 dmap file having multiple device entries as such:

```
apple sdm://./pci:pcieunis3 apple.mapp
banana sdm://./pci:pcieunis3 banana.mapp
```

If we open the devices on mtca4upy and read their 'magic' registers, reading from banana returns apple's magic number 

In fact you cannot access to banana registers. It depends on which order device is created. If banana device is opened first, the behavior switches. 

Using latest python3-mtca4upy (01.03buster1.03-0)

**Comment by mhier** [comment]
The device descriptor needs to be different for the two devices. In your case, the device descriptor is "sdm://./pci:pcieunis3" in both devices. This won't work, because you will get the same backend instance then for both devices (map file will be whichever you used first).

The solution is to move away from the (anyway deprecated) SDM syntax to the (not so) new CDD (ChimeraTK device descriptor) syntax:

```
apple  (pci:pcieunis3?map=apple.mapp)
banana  (pci:pcieunis3?map=banana.mapp)
```

The 3rd column with the map file should not be used any more.

This also has the advantage that you can directly use the CDD without the need for a DMAP file, e.g. if it is entered by the user, or if you explicitly loop over PCIe slots or so. (Most use cases should stick with the DMAP file though, for the sake of abstraction...)

**Comment by cagil-gumus** [comment]
Thank you for the explanation!
